/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uy.edu.cure.estacion.de.trabajo;

import com.sun.org.apache.xerces.internal.util.URI;
import java.awt.Image;
import java.lang.reflect.InvocationTargetException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import uy.edu.cure.servidor.central.soap.client.UsuarioWS;
import uy.edu.cure.servidor.central.soap.client.UsuarioWSImplService;
import uy.edu.cure.servidor.central.soap.client.ReservaWS;
import uy.edu.cure.servidor.central.soap.client.ReservaWSImplService;

/**
 *
 * @author SCN
 */
public class VerInfoCliente extends javax.swing.JFrame {

    private UsuarioWSImplService usuarioWSImplService;
    private ReservaWSImplService reservaWSImplService;
    private UsuarioWS portUsuario;
    private ReservaWS portReserva;
//      private ReservaWS portReserva;
//    @Jeringa (value = "reservacontroller")
//    private ReservaControllerImpl reservaController;
//    @Jeringa (value = "usuariocontroller")
//    private UsuarioControllerImpl usuariocontroller;

    /**
     * Creates new form VerInfoCliente
     */
    public VerInfoCliente() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        try {
            // JeringaInjector.getInstance().inyectar(this);
            usuarioWSImplService = new UsuarioWSImplService(new URL("http://localhost:8080/servidor-central-webapp/soap/UsuarioWSImplService?wsdl"));
        } catch (MalformedURLException e) {
            Logger.getLogger(VerInfoCliente.class.getName()).log(Level.SEVERE, null, e);
        }
        portUsuario = usuarioWSImplService.getUsuarioWSImplPort();
        portReserva = reservaWSImplService.getReservaWSImplPort();

        setLocationRelativeTo(null);
        DefaultListModel listaclientes = new DefaultListModel();
        for (int i = 0; i < portUsuario.obtenerTodosClientes().size(); i++) {
            listaclientes.add(i, portUsuario.obtenerTodosClientes().get(i).getNickName());
        }
        ListaClientes.setModel(listaclientes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListaClientes = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        NombreIndicador = new javax.swing.JLabel();
        ApellidoIndicador = new javax.swing.JLabel();
        CorreoIndicador = new javax.swing.JLabel();
        NombreAllenar = new javax.swing.JLabel();
        ApellidoAllenar = new javax.swing.JLabel();
        CorreoAllenar = new javax.swing.JLabel();
        FechaIndicador = new javax.swing.JLabel();
        FechaAllenar = new javax.swing.JLabel();
        ImagenPerfil = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaReserva = new javax.swing.JList<>();
        fechaReserva = new javax.swing.JLabel();
        precioReserva = new javax.swing.JLabel();
        estadoReserva = new javax.swing.JLabel();
        fechaReservaALlenar = new javax.swing.JLabel();
        precioReservaALlenar = new javax.swing.JLabel();
        estadoReservaALlenar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListaClientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaClientesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListaClientes);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NombreIndicador.setText("Nombre :");

        ApellidoIndicador.setText("Apellido :");

        CorreoIndicador.setText("Correo :");

        FechaIndicador.setText("Fecha naacimiento :");

        ImagenPerfil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        listaReserva.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaReservaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaReserva);

        fechaReserva.setText("Fecha: ");

        precioReserva.setText("Precio: ");

        estadoReserva.setText("Estado: ");

        precioReservaALlenar.setText(" ");

        estadoReservaALlenar.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreIndicador)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addComponent(ApellidoIndicador))
                                .addComponent(CorreoIndicador, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ApellidoAllenar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreAllenar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CorreoAllenar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaReserva)
                            .addComponent(FechaIndicador)
                            .addComponent(estadoReserva)
                            .addComponent(precioReserva))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FechaAllenar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(fechaReservaALlenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(precioReservaALlenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estadoReservaALlenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ImagenPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(ImagenPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreIndicador)
                            .addComponent(NombreAllenar, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ApellidoIndicador)
                            .addComponent(ApellidoAllenar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CorreoIndicador)
                            .addComponent(CorreoAllenar, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaAllenar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaIndicador))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaReserva)
                            .addComponent(fechaReservaALlenar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precioReserva)
                            .addComponent(precioReservaALlenar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estadoReserva)
                            .addComponent(estadoReservaALlenar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaClientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaClientesValueChanged
        fechaReservaALlenar.setText(" ");
        precioReservaALlenar.setText(" ");
        estadoReservaALlenar.setText(" ");
        int indice = ListaClientes.getSelectedIndex();
        NombreAllenar.setText(portUsuario.obtenerTodosClientes().get(indice).getNombre());
        ApellidoAllenar.setText(portUsuario.obtenerTodosClientes().get(indice).getApellido());
        CorreoAllenar.setText(portUsuario.obtenerTodosClientes().get(indice).getCorreo());
        String dia = Integer.toString(portUsuario.obtenerTodosClientes().get(indice).getFechanacimiento().getDay());
        String mes = Integer.toString(portUsuario.obtenerTodosClientes().get(indice).getFechanacimiento().getMonth());
        String anio = Integer.toString(portUsuario.obtenerTodosClientes().get(indice).getFechanacimiento().getYear());
        FechaAllenar.setText(dia + "/" + mes + "/" + anio);
        ImageIcon iconoPerfil = new ImageIcon(portUsuario.obtenerTodosClientes().get(indice).getImagenPerfil());
        Image imagenPerfil = iconoPerfil.getImage();
        Image nuevaPerfil = imagenPerfil.getScaledInstance(155, 175, java.awt.Image.SCALE_SMOOTH);
        ImageIcon nuevoIcono = new ImageIcon(nuevaPerfil);
        ImagenPerfil.setIcon(nuevoIcono);
        ImagenPerfil.setSize(155, 175);
        DefaultListModel listReservas = new DefaultListModel();
       /* for (int i = 0; i < portUsuario.obtenerTodosClientes().get(ListaClientes.getSelectedIndex()).getReservas().size(); i++) {
            listReservas.addElement(portUsuario.obtenerTodosClientes().get(indice).getReservas().get(i).getNumero());
        }*/
        listaReserva.setModel(listReservas);
    }//GEN-LAST:event_ListaClientesValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listaReservaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaReservaValueChanged
        int indice = listaReserva.getSelectedIndex();
        int indiceCliente = ListaClientes.getSelectedIndex();
/*        fechaReservaALlenar.setText(String.valueOf(portUsuario.obtenerTodosClientes().get(indiceCliente).getReservas().get(indice).getFechaCreacion().getDay()) + "/"
                + String.valueOf(portUsuario.obtenerTodosClientes().get(indiceCliente).getReservas().get(indice).getFechaCreacion().getMonth()) + "/"
                + String.valueOf(portUsuario.obtenerTodosClientes().get(indiceCliente).getReservas().get(indice).getFechaCreacion().getYear()));
        precioReservaALlenar.setText(String.valueOf(portUsuario.obtenerTodosClientes().get(indiceCliente).getReservas().get(indice).getPrecio()));
        estadoReservaALlenar.setText(portUsuario.obtenerTodosClientes().get(indiceCliente).getReservas().get(indice).getEstado());*/
    }//GEN-LAST:event_listaReservaValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerInfoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerInfoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerInfoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerInfoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerInfoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoAllenar;
    private javax.swing.JLabel ApellidoIndicador;
    private javax.swing.JLabel CorreoAllenar;
    private javax.swing.JLabel CorreoIndicador;
    private javax.swing.JLabel FechaAllenar;
    private javax.swing.JLabel FechaIndicador;
    private javax.swing.JLabel ImagenPerfil;
    private javax.swing.JList<String> ListaClientes;
    private javax.swing.JLabel NombreAllenar;
    private javax.swing.JLabel NombreIndicador;
    private javax.swing.JLabel estadoReserva;
    private javax.swing.JLabel estadoReservaALlenar;
    private javax.swing.JLabel fechaReserva;
    private javax.swing.JLabel fechaReservaALlenar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaReserva;
    private javax.swing.JLabel precioReserva;
    private javax.swing.JLabel precioReservaALlenar;
    // End of variables declaration//GEN-END:variables
}
