/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uy.edu.cure.estacion.de.trabajo;

import java.awt.Image;
import java.lang.reflect.InvocationTargetException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

import uy.edu.cure.servidor.central.soap.client.UsuarioWS;
import uy.edu.cure.servidor.central.soap.client.UsuarioWSImplService;
import uy.edu.cure.servidor.central.soap.client.ServicioWS;
import uy.edu.cure.servidor.central.soap.client.ServicioWSImplService;
import uy.edu.cure.servidor.central.soap.client.PromocionWS;
import uy.edu.cure.servidor.central.soap.client.PromocionWSImplService;

public class VerInfoPromocion extends javax.swing.JFrame {

    private UsuarioWSImplService usuarioWSImplService;
    private UsuarioWS portUsuario;
    private ServicioWSImplService servicioWSImplService;
    private ServicioWS portServicio;
    private PromocionWSImplService promocionWSImplService;
    private PromocionWS portPromocion;

    private String Separador = " // ";
    //Separador es usado para separar el nombre de la promocion del nick del proveedor
    //de esta forma se puede cumplir con los requerimientos actuales de la busqueda de una promocion

    private String proveedorAux;
    private String servicioAux;
    private String promocionAux;

    List<JLabel> imagenes;

    /**
     * Creates new form VerInfoPromocion
     */
    public VerInfoPromocion() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        try {
            promocionWSImplService = new PromocionWSImplService(new URL("http://localhost:8080/servidor-central-webapp/soap/PromocionWSImplService?wsdl"));
        } catch (MalformedURLException ex) {
            //Logger.getLogger(VerInfoPromocion.class.getName()).log(Level.SEVERE, null, ex);
        }
        portPromocion = promocionWSImplService.getPromocionWSImplPort();

        setLocationRelativeTo(null);
        /*imagenes = new ArrayList<JLabel>();
        imagenes.add(labelServicioImage1);
        imagenes.add(labelServicioImage2);
        imagenes.add(labelServicioImage3);*/
        DefaultListModel listaPromociones = new DefaultListModel();

        for (int i = 0; i < portPromocion.obtenerTodasPromociones().size(); i++) {
            String nombrePromocion = portPromocion.obtenerTodasPromociones().get(i).getNombre();
            String nickProveedor = portPromocion.obtenerTodasPromociones().get(i).getProveedor().getNickName();
            listaPromociones.addElement(nombrePromocion + Separador + nickProveedor);
        }
        listPromociones.setModel(listaPromociones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPromociones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPromociones = new javax.swing.JList<>();
        labelProveedor = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelDescuento = new javax.swing.JLabel();
        labelServicios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listServicios = new javax.swing.JList<>();
        labelServicioDescripcion = new javax.swing.JLabel();
        labelServicioPrecio = new javax.swing.JLabel();
        labelServicioOrigen = new javax.swing.JLabel();
        labelServicioDestino = new javax.swing.JLabel();
        labelServicioCategorias = new javax.swing.JLabel();
        labelServicioImage1 = new javax.swing.JLabel();
        labelServicioImage2 = new javax.swing.JLabel();
        labelServicioImage3 = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPromociones.setText("Promociones actuales: ");

        listPromociones.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPromocionesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPromociones);

        labelProveedor.setText("Proveedor: ");

        labelPrecio.setText("Precio: ");

        labelDescuento.setText("Descuento: ");

        labelServicios.setText("Servicios: ");

        listServicios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listServiciosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listServicios);

        labelServicioDescripcion.setText(" ");

        labelServicioPrecio.setText(" ");

        labelServicioOrigen.setText(" ");

        labelServicioDestino.setText(" ");

        labelServicioCategorias.setText(" ");

        labelServicioImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelServicioImage1.setText("NoImage");
        labelServicioImage1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelServicioImage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelServicioImage2.setText("NoImage");
        labelServicioImage2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelServicioImage3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelServicioImage3.setText("NoImage");
        labelServicioImage3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonBack.setText("Atras");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPromociones)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrecio)
                            .addComponent(labelProveedor)
                            .addComponent(labelDescuento)
                            .addComponent(labelServicios)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelServicioDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelServicioPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelServicioOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelServicioDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelServicioCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(buttonBack)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelServicioImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelServicioImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelServicioImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPromociones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDescuento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelServicioDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelServicioPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelServicioOrigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelServicioDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelServicioCategorias)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelServicioImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelServicioImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelServicioImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(buttonBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void listPromocionesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPromocionesValueChanged
        labelServicioImage1.setIcon(null);
        labelServicioImage2.setIcon(null);
        labelServicioImage3.setIcon(null);
        labelServicioDescripcion.setText(" ");
        labelServicioPrecio.setText(" ");
        labelServicioOrigen.setText(" ");
        labelServicioDestino.setText(" ");
        labelServicioCategorias.setText(" ");

        String aux = listPromociones.getSelectedValue();
        String[] arrayPromocionAux = aux.split(Separador);
        promocionAux = arrayPromocionAux[0];
        proveedorAux = arrayPromocionAux[1];

        portPromocion.obtenerPromocionWS(promocionAux, proveedorAux);

        String proveedor = portPromocion.obtenerPromocionWS(promocionAux, proveedorAux).getProveedor().getNickName();
        labelProveedor.setText("Proveedor: " + proveedor);
        double precio = portPromocion.obtenerPromocionWS(promocionAux, proveedorAux).getPrecioTotal();
        labelPrecio.setText("Precio: " + precio);
        int descuento = portPromocion.obtenerPromocionWS(promocionAux, proveedorAux).getDescuento();
        labelDescuento.setText("Descuento: " + descuento);

        DefaultListModel listaServicios = new DefaultListModel();
        for (int i = 0; i < portPromocion.obtenerServiciosPromoWS(promocionAux, proveedorAux).size(); i++) {
            String servicio = portPromocion.obtenerServiciosPromoWS(promocionAux, proveedorAux).get(i).getNombre();
            listaServicios.addElement(servicio);
        }
        listServicios.setModel(listaServicios);

    }//GEN-LAST:event_listPromocionesValueChanged

    private void listServiciosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listServiciosValueChanged
        try {
            servicioWSImplService = new ServicioWSImplService(new URL("http://localhost:8080/servidor-central-webapp/soap/ServicioWSImplService?wsdl"));
        } catch (MalformedURLException ex) {
            //Logger.getLogger(VerInfoProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        portServicio = servicioWSImplService.getServicioWSImplPort();

        servicioAux = listServicios.getSelectedValue();

        labelServicioDescripcion.setText(portServicio.obtenerServicioWS(servicioAux, proveedorAux).getDescripcion());
        labelServicioPrecio.setText("Precio: " + String.valueOf(portServicio.obtenerServicioWS(servicioAux, proveedorAux).getPrecio()));
        labelServicioOrigen.setText("Ciudad de origen: " + portServicio.obtenerServicioWS(servicioAux, proveedorAux).getOrigen().getNombre());
        if (portServicio.obtenerServicioWS(servicioAux, proveedorAux).getDestino() == null) {
            labelServicioDestino.setText("No hay ciudad de destino");
        } else {
            labelServicioDestino.setText("Ciudad de destino: " + portServicio.obtenerServicioWS(servicioAux, proveedorAux).getDestino().getNombre());
        }

        //Categorias del servicio
        String categorias = "Categorias: ";

        for (int i = 0; i < portServicio.obtenerCategoriasServicioWS(servicioAux, proveedorAux).size(); i++) {
            if (i > 0) {
                categorias = categorias + ", ";
            }
            categorias = categorias + portServicio.obtenerCategoriasServicioWS(servicioAux, proveedorAux).get(i).getNombre();

        }
        labelServicioCategorias.setText(categorias);

        //Imagenes del servicio
        for (int i = 0; i < portServicio.obtenerImagenesServicioWS(servicioAux, proveedorAux).size(); i++) {
            ImageIcon imageIcon = new ImageIcon(portServicio.obtenerImagenesServicioWS(servicioAux, proveedorAux).get(i));
            Image image = imageIcon.getImage();
            Image imageFinal = image.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            ImageIcon imageIconFinal = new ImageIcon(imageFinal);
            imagenes.get(i).setIcon(imageIconFinal);
        }

    }//GEN-LAST:event_listServiciosValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerInfoPromocion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerInfoPromocion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerInfoPromocion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerInfoPromocion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerInfoPromocion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDescuento;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelPromociones;
    private javax.swing.JLabel labelProveedor;
    private javax.swing.JLabel labelServicioCategorias;
    private javax.swing.JLabel labelServicioDescripcion;
    private javax.swing.JLabel labelServicioDestino;
    private javax.swing.JLabel labelServicioImage1;
    private javax.swing.JLabel labelServicioImage2;
    private javax.swing.JLabel labelServicioImage3;
    private javax.swing.JLabel labelServicioOrigen;
    private javax.swing.JLabel labelServicioPrecio;
    private javax.swing.JLabel labelServicios;
    private javax.swing.JList<String> listPromociones;
    private javax.swing.JList<String> listServicios;
    // End of variables declaration//GEN-END:variables
}
