/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uy.edu.cure.estacion.de.trabajo;

import java.awt.Image;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import uy.edu.cure.servidor.central.dto.Servicio;
import uy.edu.cure.servidor.central.lib.*;
import uy.edu.cure.servidor.central.lib.jeringa.Jeringa;
import uy.edu.cure.servidor.central.lib.jeringa.JeringaInjector;

/**
 *
 * @author Rodrigo "Lobo Plateado" Pérez
 */
public class VerInfoPromocion extends javax.swing.JFrame {

    @Jeringa (value = "promocioncontroller")
    PromocionControllerImpl promocionController;
    @Jeringa (value = "serviciocontroller")
    ServicioControllerImpl servicioController;
    List<JLabel> imagenes;

    /**
     * Creates new form VerInfoPromocion
     */
    public VerInfoPromocion() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
          try {
            JeringaInjector.getInstance().inyectar(this);
        } catch (ClassNotFoundException | NoSuchMethodException | SecurityException | InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
            e.printStackTrace();
        }
        
        setLocationRelativeTo(null);
        imagenes = new ArrayList<JLabel>();
        imagenes.add(labelServicioImage1);
        imagenes.add(labelServicioImage2);
        imagenes.add(labelServicioImage3);
        DefaultListModel listaPromociones = new DefaultListModel();
        for (int i = 0; i < promocionController.obtenerTodasPromociones().size(); i++) {
            String nombrePromocion = promocionController.obtenerTodasPromociones().get(i).getNombre();
            listaPromociones.addElement(nombrePromocion);
        }
        listPromociones.setModel(listaPromociones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPromociones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPromociones = new javax.swing.JList<>();
        labelProveedor = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelDescuento = new javax.swing.JLabel();
        labelServicios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listServicios = new javax.swing.JList<>();
        labelServicioDescripcion = new javax.swing.JLabel();
        labelServicioPrecio = new javax.swing.JLabel();
        labelServicioOrigen = new javax.swing.JLabel();
        labelServicioDestino = new javax.swing.JLabel();
        labelServicioCategorias = new javax.swing.JLabel();
        labelServicioImage1 = new javax.swing.JLabel();
        labelServicioImage2 = new javax.swing.JLabel();
        labelServicioImage3 = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPromociones.setText("Promociones actuales: ");

        listPromociones.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPromocionesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPromociones);

        labelProveedor.setText("Proveedor: ");

        labelPrecio.setText("Precio: ");

        labelDescuento.setText("Descuento: ");

        labelServicios.setText("Servicios: ");

        listServicios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listServiciosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listServicios);

        labelServicioDescripcion.setText(" ");

        labelServicioPrecio.setText(" ");

        labelServicioOrigen.setText(" ");

        labelServicioDestino.setText(" ");

        labelServicioCategorias.setText(" ");

        labelServicioImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelServicioImage1.setText("NoImage");
        labelServicioImage1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelServicioImage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelServicioImage2.setText("NoImage");
        labelServicioImage2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelServicioImage3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelServicioImage3.setText("NoImage");
        labelServicioImage3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonBack.setText("Atras");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPromociones)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrecio)
                            .addComponent(labelProveedor)
                            .addComponent(labelDescuento)
                            .addComponent(labelServicios)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelServicioDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelServicioPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelServicioOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelServicioDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelServicioCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(buttonBack)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelServicioImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelServicioImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelServicioImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPromociones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDescuento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelServicioDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelServicioPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelServicioOrigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelServicioDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelServicioCategorias)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelServicioImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelServicioImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelServicioImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(buttonBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void listPromocionesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPromocionesValueChanged
        labelServicioImage1.setIcon(null);
        labelServicioImage2.setIcon(null);
        labelServicioImage3.setIcon(null);
        labelServicioDescripcion.setText(" ");
        labelServicioPrecio.setText(" ");
        labelServicioOrigen.setText(" ");
        labelServicioDestino.setText(" ");
        labelServicioCategorias.setText(" ");
        int indicePromocion = listPromociones.getSelectedIndex();
        String proveedor = promocionController.obtenerTodasPromociones().get(indicePromocion).getProveedor().getNickName();
        labelProveedor.setText("Proveedor: " + proveedor);
        double precio = promocionController.obtenerTodasPromociones().get(indicePromocion).getPrecioTotal();
        labelPrecio.setText("Precio: " + precio);
        int descuento = promocionController.obtenerTodasPromociones().get(indicePromocion).getDescuento();
        labelDescuento.setText("Descuento: " + descuento);
        DefaultListModel listaServicios = new DefaultListModel();
        for (int i = 0; i < promocionController.obtenerTodasPromociones().get(indicePromocion).getServicios().size(); i++) {
            String servicio = promocionController.obtenerTodasPromociones().get(indicePromocion).getServicios().get(i).getNombre();
            listaServicios.addElement(servicio);
        }
        listServicios.setModel(listaServicios);
    }//GEN-LAST:event_listPromocionesValueChanged

    private void listServiciosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listServiciosValueChanged
        if (listServicios.getSelectedIndex() >= 0) {
            String nombreServicio = listServicios.getSelectedValue();
            int indicePromocion = listPromociones.getSelectedIndex();
            String nombreProveedor = promocionController.obtenerTodasPromociones().get(indicePromocion).getProveedor().getNickName();
            Servicio servicio = servicioController.obtenerServicio(nombreServicio, nombreProveedor);
            labelServicioDescripcion.setText(servicio.getDescripcion());
            labelServicioPrecio.setText("Precio: " + String.valueOf(servicio.getPrecio()));
            labelServicioOrigen.setText("Ciudad de origen: " + servicio.getOrigen().getNombre());
            if (servicio.getDestino() == null) {
                labelServicioDestino.setText("No hay ciudad de destino");
            } else {
                labelServicioDestino.setText("Ciudad de destino: " + servicio.getDestino().getNombre());
            }
            String categorias = "Categorias: ";
            for (int i = 0; i < servicio.getCategorias().size(); i++) {
                categorias = categorias + servicio.getCategorias().get(i).getNombre();
                categorias = categorias + " ";
            }
            labelServicioCategorias.setText(categorias);
            for (int i = 0; i < servicio.getImagenes().size(); i++) {
                ImageIcon imageIcon = new ImageIcon(servicio.getImagenes().get(i));
                Image image = imageIcon.getImage();
                Image imageFinal = image.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
                ImageIcon imageIconFinal = new ImageIcon(imageFinal);
                imagenes.get(i).setIcon(imageIconFinal);
            }
        }
    }//GEN-LAST:event_listServiciosValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerInfoPromocion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerInfoPromocion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerInfoPromocion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerInfoPromocion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerInfoPromocion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDescuento;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelPromociones;
    private javax.swing.JLabel labelProveedor;
    private javax.swing.JLabel labelServicioCategorias;
    private javax.swing.JLabel labelServicioDescripcion;
    private javax.swing.JLabel labelServicioDestino;
    private javax.swing.JLabel labelServicioImage1;
    private javax.swing.JLabel labelServicioImage2;
    private javax.swing.JLabel labelServicioImage3;
    private javax.swing.JLabel labelServicioOrigen;
    private javax.swing.JLabel labelServicioPrecio;
    private javax.swing.JLabel labelServicios;
    private javax.swing.JList<String> listPromociones;
    private javax.swing.JList<String> listServicios;
    // End of variables declaration//GEN-END:variables
}
